/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivateUser: typeof import('./src/components/atoms/ActivateUser.vue')['default']
    BackButton: typeof import('./src/components/atoms/BackButton.vue')['default']
    BanToggle: typeof import('./src/components/atoms/BanToggle.vue')['default']
    BaseBadge: typeof import('./src/components/atoms/BaseBadge.vue')['default']
    BaseButton: typeof import('./src/components/atoms/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/atoms/BaseInput.vue')['default']
    ClearIconButton: typeof import('./src/components/atoms/ClearIconButton.vue')['default']
    DeleteButton: typeof import('./src/components/atoms/DeleteButton.vue')['default']
    Error: typeof import('./src/components/atoms/Error.vue')['default']
    Footer: typeof import('./src/components/atoms/Footer.vue')['default']
    FormButton: typeof import('./src/components/atoms/FormButton.vue')['default']
    FormLayout: typeof import('./src/components/layouts/FormLayout.vue')['default']
    HorizontalOptionsList: typeof import('./src/components/molecules/HorizontalOptionsList.vue')['default']
    ListLayout: typeof import('./src/components/layouts/ListLayout.vue')['default']
    ListRouterLinksToItems: typeof import('./src/components/molecules/ListRouterLinksToItems.vue')['default']
    ListRouterLInkToItem: typeof import('./src/components/molecules/ListRouterLInkToItem.vue')['default']
    ListWithoutLinks: typeof import('./src/components/molecules/ListWithoutLinks.vue')['default']
    Loading: typeof import('./src/components/atoms/Loading.vue')['default']
    NavBar: typeof import('./src/components/organisms/NavBar.vue')['default']
    PaginationMenu: typeof import('./src/components/molecules/PaginationMenu.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowPasswordButton: typeof import('./src/components/ShowPasswordButton.vue')['default']
    StartNavBar: typeof import('./src/components/organisms/StartNavBar.vue')['default']
    Success: typeof import('./src/components/atoms/Success.vue')['default']
    TicketBadges: typeof import('./src/components/molecules/TicketBadges.vue')['default']
    TicketBottom: typeof import('./src/components/molecules/TicketBottom.vue')['default']
    TicketChat: typeof import('./src/components/molecules/TicketChat.vue')['default']
    TicketControls: typeof import('./src/components/molecules/TicketControls.vue')['default']
    TicketDetails: typeof import('./src/components/molecules/TicketDetails.vue')['default']
    TicketLayout: typeof import('./src/components/layouts/TicketLayout.vue')['default']
    TicketNameCard: typeof import('./src/components/molecules/TicketNameCard.vue')['default']
    Toast: typeof import('./src/components/molecules/Toast.vue')['default']
    Toolbar: typeof import('./src/components/molecules/Toolbar.vue')['default']
    ToolBar: typeof import('./src/components/molecules/ToolBar.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    UserBadges: typeof import('./src/components/molecules/UserBadges.vue')['default']
    UserToolbar: typeof import('./src/components/molecules/UserToolbar.vue')['default']
    ZgrzytFooter: typeof import('./src/components/atoms/ZgrzytFooter.vue')['default']
  }
}
